export const seedAdvisors = [
    {
        id: "CE6622",
        name: "Suraj Gupta",
        title: "Senior Life Insurance Advisor",
        company: "Life Insurance Corporation of India (LIC)",
        phone: "8103747279",
        email: "suraj.gupta817@yahoo.in",
        licenseNumber: "IRDAI/CA/1234567890",
        avatarInitials: "SG",
        experienceYears: 13,
        clientsServed: 2400,
        greeting: "I'll personally help you find the right cover for your family.",
    },
    {
        id: "CE8841",
        name: "Prakash Gupta",
        title: "Certified Financial Planner",
        company: "Life Insurance Corporation of India (LIC)",
        phone: "9691383416",
        email: "prakash.gupta817@yahoo.in",
        licenseNumber: "IRDAI/CA/67890",
        avatarInitials: "PG",
        experienceYears: 8,
        clientsServed: 1800,
        greeting: "Let me guide you to the protection your loved ones deserve.",
    },
];
